### PR TITLE
Features

### PR DESCRIPTION
**Pull request by ricardo123321**
this is a project in which I made use of bootstrap to align the elements in different columns to create a replica of the Newsweek resizable  front page, I also made use of some basic CSS

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @ricardo123321, great work for a first attempt 👍 very responsive 🙂 , However, since our main focus for this project is using bootstrap classes everywhere, and making an exact clone of the Newsweek.com, let us make a little improvement to our project 👐 . Find comments below:
- Let us fix stickler error, click on the details and fix the error in the CSS file
-  Let us fix the nav. We can increase the width and also let us remove the hamburger button. Kindly check the images below for more details
```Our version```
nes1
```Original version```
nes
- Let us compare and fix the images below, consider background-color and font
```Our version```
nes3
```Original version```
nes2
Let us check for that in the other sections and make the changes
- Let us use more of the bootstrap classes, let us reduce the custom CSS and use more of bootstrap classes. Example, there are bootstrap classes for the following
```.bt-sub {
  align-items: center;
  display: flex;
  margin-top: 23px;
}
```
- Kindly add links to the footer
- Let us fix 60+ warnings and errors returned by the [w3validator](https://validator.w3.org/)
- Let us add our email to the author section of our README file nad improve on the description
- Let us edit our PR so we have a title and a short description of the project

Kindly make these changes and submit another code review 👍 
Happy coding_ 👨‍💻 
Daniel Larbi Addo on slack

**Comment by Dandush03** [comment]
# :red_circle: Status Require: changes :muscle: 
### Hey @ricardo123321  :wave: 
## Good attempts on this one :muscle: :+1: 

### This page is a clone page from the [newsweek](https://www.newsweek.com/), therefore there are a few changes you have to fix in order to achieve it

## Here are the issues to address to get the project meet the requirement:wink:

---

# Desktop Resolution (min-width:1024px)

---

## Header
- [ ] Hamburger button should not be visible
##### Required:
Screenshot from 2020-04-09 08-43-08
##### Yours: 
Screenshot from 2020-04-09 08-42-59

## Nav-bar
- [ ] The Nav-Bar element aren't aligned
- [ ] The nav should not take the 100% of the width
##### Required:
Screenshot from 2020-04-09 08-42-46
##### Yours: 
Screenshot from 2020-04-09 08-41-06

## Opinion section
- [ ] The title have a 'debate' text on top of it?
- [ ] Need more padding for text and images
##### Required:
Screenshot from 2020-04-09 08-43-30
##### Yours: 
Screenshot from 2020-04-09 08-41-33

## The Author section 
- [ ] The image should be in front of the line
##### Required:
Screenshot from 2020-04-09 08-43-58
##### Yours: 
Screenshot from 2020-04-09 08-41-49

## The Magazine section
- [ ] Left most image should be size the same high as the other images + text
##### Required:
Screenshot from 2020-04-09 09-02-16
##### Yours: 
Screenshot from 2020-04-09 08-42-07

---

# Pad Resolution (Width: 768px)

---

## Opinion section
- [ ] Fix margin
- [ ] Fix padding
- [ ] Fix alignments
##### Required:
Screenshot from 2020-04-09 08-45-37
##### Yours: 
Screenshot from 2020-04-09 08-45-16

## Footer section
- [ ] Fix alignments
- [ ] Fix Logo Color
- [ ] Fix links Color
##### Required:
Screenshot from 2020-04-09 08-46-49
##### Yours: 
Screenshot from 2020-04-09 08-46-40

---

### Notice that I'm not repeating my self in each section. Be sure that you have all previews error fixed in different screen sizes

---

# [IMPORTANT]

---

## as requested before from my college please address the fallowing issues

- [ ] Fix the PR so it would look more professional, Add some details of what you've done in this branch
- [ ] this project as a hard requirement is the use of Bootstrap Css classes **everywhere** for styling (for example [Grid layout](https://getbootstrap.com/docs/4.3/layout/overview/) and [Flex](https://getbootstrap.com/docs/4.3/layout/utilities-for-layout/#flexbox-options)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/using_bootstrap/bootstrap_classes_requirement.png) from [Pathwrigth](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540308/))

---




## Kindly address all these changes and submit a new code review

### Happy coding:computer: 

#### Daniel Laloush

**Review by men32z — CHANGES_REQUESTED** [review]
Hey @ricardo123321 !
## Good job on this project! 👍

There are still some changes 👇 you need to implement to approve this request 🔍
#### please check your changes in both browsers Firefox and Chrome and be sure it works properly.

### Required changes
sc1
- [ ] the previous TSE pointed that the navbar has to be fixed, take a look in Firefox and Chrome and be sure that works properly in both.

sc2
- [ ] as the previous TSE required kindly fix the size of this section images.

#### take a look in this image and make the following changes, yours is the left one.
sc
- [ ] the navbar should be sticky(fixed position). 
- [ ] add the right colors to the "subscribe" buttons.
- [ ] the fonts on the subscribe section look different, for instance the size. but could be also the font family.
- [ ] the items in the footer section doesn't have the "|" margin separator in the smallest version.
- [ ] those items should be links.

#### take a look in this image and make the following changes, yours is the left one.
bbbb
- [ ] the content of the website should have a white background color, be sure that it is aligned to the header (navbar) and it has a max-width as the navbar has. 
- [ ] check the previous image and be sure that this white container is full width in smallest screens.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@men32z)
I would be happy to help! :hammer:

--Luis Preza

**Comment by christianotieno** [comment]
## Pull Request under review by Christian Otieno (TSE)

**Review by christianotieno — APPROVED** [review]
# PROJECT APPROVED :champagne:
Excellent job on this project @ricardo123321 . :fireworks: Keep it up.
##
***All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.***
- Congratulations! :+1:
- You can now merge to master and I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

**Pull request merged**
